name: Build Windows

on:
  workflow_dispatch:

permissions: write-all

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        env:
          npm_config_arch: ${{ matrix.arch }}
          npm_config_target_arch: ${{ matrix.arch }}
        run: pnpm install

      - name: Prepare
        run: pnpm prepare --${{ matrix.arch }}

      - name: Build
        env:
          npm_config_arch: ${{ matrix.arch }}
          npm_config_target_arch: ${{ matrix.arch }}
        run: pnpm build:win --${{ matrix.arch }}

      - name: Add Portable Flag
        run: |
          New-Item -Path "PORTABLE" -ItemType File
          Get-ChildItem dist/*portable.7z | ForEach-Object {
            7z a $_.FullName PORTABLE
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-custom
          path: |
            dist/*setup.exe
            dist/*portable.7z
          if-no-files-found: error
